openapi: 3.0.0
info:
  description: |
    This is a sample Petstore server.  You can find
    out more about Swagger at
    [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).
  version: 1.0.0
  title: Swagger Petstore
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/ravlio/optiprism/1.0.0
  - url: https://petstore.swagger.io/v2
tags:
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
paths: { }
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
        teams:
          type: array
          items:
            type: integer
        projects:
          type: array
          items:
            type: object
            properties:
              projectId:
                type: integer
                format: int64
              role:
                type: string
        status:
          type: string
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        name:
          type: string
        sessionTimeoutSeconds:
          type: integer
        teams:
          type: array
          items:
            type: integer
        users:
          type: array
          items:
            type: integer
    Organization:
      type: object
      properties:
        teams:
          type: array
          items:
            type: integer
        users:
          type: array
          items:
            type: integer
    Event:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
    CustomEvent:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
    EventProperty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        eventId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        displayName:
          type: string
        type:
          $ref: '#/components/schemas/DataType'
        required:
          type: boolean
        nullable:
          type: boolean
        isArray:
          type: boolean
        isDictionary:
          type: boolean
        dictionaryType:
          $ref: '#/components/schemas/DataType'
        tags:
          type: array
          items:
            type: string
    EventCustomProperty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        eventId:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        type:
          $ref: '#/components/schemas/DataType'
        nullable:
          type: boolean
        isArray:
          type: boolean
        tags:
          type: array
          items:
            type: string
    UserProperty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        type:
          $ref: '#/components/schemas/DataType'
        nullable:
          type: boolean
        isArray:
          type: boolean
        tags:
          type: array
          items:
            type: string
    UserCustomProperty:
      type: object
      properties:
        id:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        createdBy:
          type: integer
          format: int64
        updatedBy:
          type: integer
          format: int64
        projectId:
          type: integer
          format: int64
        isSystem:
          type: boolean
        status:
          type: string
          enum:
            - enabled
            - disabled
        name:
          type: string
        description:
          type: string
        type:
          $ref: '#/components/schemas/DataType'
        nullable:
          type: boolean
        isArray:
          type: boolean
        tags:
          type: array
          items:
            type: string
    EventSegmentationRequest:
      type: object
      properties:
        events:
          type: object
          properties:
            allOf:
              - $ref: '#/components/schemas/EventRef'
              - type: object
                  type: object
                  properties:
                    filters:
                      type: array
                      items:
                        type: object
                        properties:
                          name:
                            type: string
    Filter:
      type: object
    EventRef:
      type: object
      properties:
        eventType:
          $ref: '#/components/schemas/EventType'
        eventId:
          type: integer
          format: int64

    EventType:
      type: string
      enum:
        - regular
        - custom
    PropertyType:
      type: string
      enum:
        - event
        - eventCustom
        - user
        - userCustom
    DataType:
      type: string
      enum:
        - string
        - float64
        - int8
        - int16
        - int32
        - int64
        - uint8
        - uint16
        - uint32
        - uint64
        - boolean
    DataTypeFamily:
      type: string
      enum:
        - string
        - number
        - int8
        - int16
        - int32
        - int64
        - uint8
        - uint16
        - uint32
        - uint64
        - boolean
